### PR TITLE
F shipyard logs

### PR DESCRIPTION
**Pull request by Ishan27g**
Adds `shipyard log`
  
  `./shipyard log` - list blueprint resources (unsure about what to list here, could also cover [51](https://github.com/shipyard-run/shipyard/issues/51))
  `./shipyard log containers` - logs all containers running in shipyard
  `./shipyard log cluster $clusterName` - logs all pods running in a shipyard k3s cluster (Unsure about nameSpace and filtering)
  `go test cmd/log_test.go cmd/log.go -v -cover -race` - tests the above 3 commands,
        but it requires a specific blueprint to be running in the background. I'm not able to implement this
        as a functional test. The test method has been commented out so as to not run during `make test` 

Adding logs for a specific container/pod will be simple, I am unsure of what cli flags/args to use.
Auto-complete is not yet added although the data expected by its handler has been implemented. Im not able to get it to work though.

### CODE REVIEW

**Comment by nicholasjackson** [comment]
Thanks @Ishan27g awesome PR, I have a few comments on this and will run through in more detail this evening.

**Comment by nicholasjackson** [comment]
@Ishan27g thank you so much for this PR and sorry for the delay in getting this merged for you, I had a few things in flight that I needed to get in before I could merge this.

I could not make changes directory to your PR so I bundled this up with a different one.

https://github.com/shipyard-run/shipyard/pull/134

Hope you don't mind but I made a couple of changes just to bring things in line with the style used in other commands and I temporarily removed the capability to get the logs from clusters.  I do want to implement this but the question is what the best UX is.  Displaying all logs from a cluster in the case of Kubernetes would be very noisy and possibly not much value, displaying logs from a namespace or specific pod would be way more useful output. But then we need consistency for Nomad jobs I am kind of leaning towards something like...

```
shipyard log k8s_cluster.dev deployment/web poabsdr1242-dev
```

This would follow the standard Kubernetes logs format, but, to get the name of the deployment you would have to use kubectl get pods, etc, so why not use kubectl logs deployment/...

Where I think Shipyard can add a huge UX boost would be with autocomplete, if you could do `shipyard logs k8s_cluster.dev <tab> <see list of pods and deployments>` this would be pretty nice.

**Comment by Ishan27g** [comment]
Thanks @nicholasjackson, I will go through it and learn from the changes you have made. I was totally confused about how to go about logs for Kubernetes and Nomad as I did not have much experience with them. 

> This would follow the standard Kubernetes logs format, but, to get the name of the deployment you would have to use kubectl get pods, etc, so why not use kubectl logs deployment/...
> 

Agreed, a little off topic but would a simple web UI be of any good for viewing logs? [Dozzle](https://dozzle.dev/) is pretty nice, but it is limited to single docker container. I have been working on a personal project which is similar to Dozzle but additionally allows Kubernetes plus aggregated logs from a docker-swarm or a kubernetes-cluster. Im using the docker and kubernetes go-sdk, so it is pretty easy to get Shipyard logs from it. I am quite close to finishing this project, I can share a link if you would like.

> Where I think Shipyard can add a huge UX boost would be with autocomplete, if you could do `shipyard logs k8s_cluster.dev <tab> <see list of pods and deployments>` this would be pretty nice.

Awesome, I can pick this up, but it might take a bit longer this time around as my Uni just resumed.

**Comment by nicholasjackson** [comment]
@Ishan27g I think a web UI could be really useful, one of the things I find so cumbersome when developing on clusters like Kubernetes or Nomad is getting access to logs. Basically, the approach is something like the following...

```
kubectl get pods --all-namespaces
<find pod name>
kubectl describe pod
<find container name>
kubectl logs -it <pod name> -c <container name>
```

This is obviously the worst-case and there are better ways to do this such as getting logs by deployment or by pod metadata but all of that implies that you know what is going on inside the cluster. Dozzle is pretty cool and I can see how a UI would really help with the discoverability and viewing of logs. However, one thing we should be careful about is being too opinionated on log viewing. For example, I use TMUX to split my terminal window into multiple panes, I find it super useful to be able to tail logs in one terminal pane while executing commands or something in another. Being able to keep the focus on the task at hand is something that is very productive for me. But others may prefer a browser-based approach.

Shipyard has a built-in API that allows terminal connections to containers, I think it would be pretty trivial to expose logs via this mechanism too. Ideally, this could also be built out to provide information on the resources running Shipyard, recursively drilling into this to obtain info like jobs or pods and the containers within them. If I have time I might try to make a start on this API, building a UI from this would then be much simpler.

**Comment by Ishan27g** [comment]
> Shipyard has a built-in API that allows terminal connections to containers, I think it would be pretty trivial to expose logs via this mechanism too. Ideally, this could also be built out to provide information on the resources running Shipyard, recursively drilling into this to obtain info like jobs or pods and the containers within them. If I have time I might try to make a start on this API, building a UI from this would then be much simpler.

Hi @nicholasjackson, I agree, such an API would make it really easy to implement a simple UI for logs. I think a web-view could be pretty useful, specially for Kubernetes and Nomad. Something similar to this UI Ive been working on ->

https://user-images.githubusercontent.com/63078216/129466219-d2cc86e2-b05c-4064-9fdc-02e18d7234a3.mov

**Pull request closed without merging**
